/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LessonPlanRouteImport } from './routes/lesson-plan'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlanRoute = LessonPlanRouteImport.update({
  id: '/lesson-plan',
  path: '/lesson-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lesson-plan': typeof LessonPlanRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lesson-plan': typeof LessonPlanRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/lesson-plan': typeof LessonPlanRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/lesson-plan'
    | '/practice'
    | '/pricing'
    | '/sitemap.xml'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/lesson-plan'
    | '/practice'
    | '/pricing'
    | '/sitemap.xml'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/lesson-plan'
    | '/practice'
    | '/pricing'
    | '/sitemap.xml'
    | '/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LessonPlanRoute: typeof LessonPlanRoute
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubjectsRoute: typeof SubjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plan': {
      id: '/lesson-plan'
      path: '/lesson-plan'
      fullPath: '/lesson-plan'
      preLoaderRoute: typeof LessonPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LessonPlanRoute: LessonPlanRoute,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubjectsRoute: SubjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
